### ISSUE TITLE
Select boxes with optgroups having duplicate issue in Bootstrap 5

### ISSUE THREAD

**Issue by ajaypatelaj** [snapappointments/bootstrap-select#2607]
Select boxes with optgroups having duplicate items issue in Bootstrap 5 as per the attached snap.

You can also test in on plnkr demo as mentioned below.

Guidelines for bug reports:

1. **Provide environment details.** Provide your operating system, browser(s),
jQuery version: as per plunker demo 
Bootstrap version: 5.0.1
Bootstrap-select: v1.14.0-beta2

2. **Create an isolated and reproducible test case.** Create a reduced test
Demo: https://plnkr.co/edit/gqrED8PRIUcJtTSL?preview

<img width="635" alt="Screenshot 2021-05-14 at 12 29 09 PM" src="https://user-images.githubusercontent.com/749684/118234083-7d0a4180-b4b0-11eb-910c-a1833cbaf063.png">

It should be like 

<img width="674" alt="Screenshot 2021-05-14 at 12 35 04 PM" src="https://user-images.githubusercontent.com/749684/118234385-dd997e80-b4b0-11eb-9bf9-d82781947e37.png">

Thanks in advance! 🙏
Thanks a ton for providing the Bootstrap 5 support 🎉

**Comment by shankyag** [comment]
Hello,
Did you get the solution. because the same thing happening to me also.

**Comment by ajaypatelaj** [comment]
> Hello,
> Did you get the solution. because the same thing happening to me also.

Not yet :(

**Comment by mrlife** [comment]
This issue was introduced with the first beta of 1.14 and affects Bootstrap 4.6 as well.

See: https://plnkr.co/edit/4XunklzplCVLrgAA

I submitted a PR that should fix the issue. It's a simple change and hopefully doesn't cause any other issue.

**Comment by shankyag** [comment]
FIxed.
https://github.com/snapappointments/bootstrap-select/issues/2562#issuecomment-809732488

**Comment by wastzzz** [comment]
Any news on this fix?

**Comment by Josh-Sul** [comment]
Any updates, please?

**Comment by qbecker** [comment]
Is there a solution to this?

**Comment by farhadmammadli** [comment]
@caseyjhol your merge does not have any changes, we still have the issue

**Comment by farhadmammadli** [comment]
For anyone looking for cdn hosted file with fix applied (tested with bootstrap 5.0.1):
https://cdn.jsdelivr.net/gh/farhadmammadli/bootstrap-select@main/js/bootstrap-select.min.js
(thanks to @sjamestasc)

**Comment by Luigii1506** [comment]
> For anyone looking for cdn hosted file with fix applied (tested with bootstrap 5.0.1): https://cdn.jsdelivr.net/gh/farhadmammadli/bootstrap-select@main/js/bootstrap-select.min.js (thanks to @sjamestasc)

Working in bootstrap 5.0.2, thank you so much

**Comment by lolbat** [comment]
Thanks very much. We were going crazy trying to fix this

**Comment by sbraaa** [comment]
Thanks

> For anyone looking for cdn hosted file with fix applied (tested with bootstrap 5.0.1): https://cdn.jsdelivr.net/gh/farhadmammadli/bootstrap-select@main/js/bootstrap-select.min.js (thanks to @sjamestasc)

Thank you!

**Comment by SanderVanKeer** [comment]
is there a tag where this fix has been applied to? I would like to install/update it via composer

**Comment by nkavian** [comment]
> For anyone looking for cdn hosted file with fix applied (tested with bootstrap 5.0.1): https://cdn.jsdelivr.net/gh/farhadmammadli/bootstrap-select@main/js/bootstrap-select.min.js (thanks to @sjamestasc)

This was a life saver. But, the `title` on `select` and `optgroup` don't work.

**Comment by rbferreyra** [comment]
There is a PR #2600. But the PR was not merged into branch v1.14.-beta2. Why?
